# Generated by Django 3.2.9 on 2021-11-16 12:59

from django.db import migrations, models
import django.utils.timezone
import django_bleach.models
import modules.tweets.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('content', models.TextField(help_text='264 characters maximal or fewer', max_length=264, verbose_name='comment content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseUserLikedTweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='tweet id')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('tags', django_bleach.models.BleachField(blank=True, help_text='100 characters or fewer. Letters, underscore and white space only', max_length=100, validators=[modules.tweets.models.tweet_tags_validator])),
                ('content', models.TextField(blank=True, help_text='264 characters maximal or fewer', max_length=264, verbose_name='tweet content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tweet created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tweet updated')),
            ],
        ),
    ]
