# Generated by Django 3.2.9 on 2021-11-21 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responseuserlikedtweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_tweet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responseuserlikedtweet',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
        migrations.AddField(
            model_name='responselike',
            name='tweet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tweets.tweet'),
        ),
        migrations.AddField(
            model_name='responselike',
            name='user',
            field=models.ManyToManyField(related_name='likes_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsecomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsecomment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweets.tweet'),
        ),
    ]
